export const plantData = [
  {
    id: '1',
    name: 'Peace Lily',
    price: 20,
    category: 'Air Purifying',
    description: 'Cleans indoor air',
    image: 'https://via.placeholder.com/150?text=Peace+Lily',
  },
  {
    id: '2',
    name: 'Lavender',
    price: 15,
    category: 'Aromatic',
    description: 'Smells great and calms the mind.',
    image: 'https://via.placeholder.com/150?text=Lavender',
  },
  {
    id: '3',
    name: 'Snake Plant',
    price: 18,
    category: 'Low Light',
    description: 'Thrives in low light, hard to kill.',
    image: 'https://via.placeholder.com/150?text=Snake+Plant',
  },
  {
    id: '4',
    name: 'Aloe Vera',
    price: 12,
    category: 'Air Purifying',
    description: 'Soothing and easy to care for.',
    image: 'https://via.placeholder.com/150?text=Aloe+Vera',
  },
  {
    id: '5',
    name: 'Rosemary',
    price: 10,
    category: 'Aromatic',
    description: 'Great for cooking and fragrance.',
    image: 'https://via.placeholder.com/150?text=Rosemary',
  },
  {
    id: '6',
    name: 'ZZ Plant',
    price: 25,
    category: 'Low Light',
    description: 'Tough and elegant.',
    image: 'https://via.placeholder.com/150?text=ZZ+Plant',
  },
];
